name: Routine Validation

on:
  push:
    branches:
    - main
  pull_request:
  
jobs:
  format-validation:
    name: Format
    runs-on: ${{ vars.RUNNER }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Select Xcode Version
        run: sudo xcode-select --switch ${{ vars.TOOLPATH }}
      - name: Verify Format
        run: swiftformat Sources Tests --lint --dryrun
  linter-validation:
    name: Linter
    runs-on: ${{ vars.RUNNER }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Select Xcode Version
        run: sudo xcode-select --switch ${{ vars.TOOLPATH }}
      - name: Install Linter
        run: brew install swiftlint
      - name: Run Linter
        run: swiftlint Sources Tests --quiet 
  build-and-test-package:
    strategy:
      matrix:
        platforms: ${{ fromJSON(vars.PLATFORMS) }}
      fail-fast: false
    name: Build and Test ${{ matrix.platforms.name }}
    runs-on: ${{ vars.RUNNER }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Select Xcode Version
        run: sudo xcode-select --switch ${{ vars.TOOLPATH }}
      - name: Build and Test
        run: xcodebuild test -scheme swift-resource-provider -destination '${{ matrix.platforms.destination }}' -skipMacroValidation